# Generated by Django 5.0.1 on 2024-01-12 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manufacturer',
            old_name='name',
            new_name='region',
        ),
    ]
