# Generated by Django 5.0.1 on 2024-01-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('year', models.PositiveIntegerField()),
                ('manufacturer', models.ManyToManyField(related_name='cars', to='manufacturer.manufacturer')),
            ],
        ),
    ]
