# Generated by Django 5.0.1 on 2024-01-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_remove_car_manufacturer_car_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
