# Generated by Django 5.0.1 on 2024-01-17 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='bio',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
    ]
